pipeline {
    agent { label 'docker-agent' }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/Vandu0409/jenkins.git'
            }
        }

        stage('Build') {
            steps {
                dir('javaapp-standalone') {
                    sh "mvn clean package -DskipTests"
                }
            }
        }

        stage('Test') {
            steps {
                dir('javaapp-standalone') {
                    sh "mvn test"
                }
            }
        }

        // stage('SonarQube Analysis') {
        //  steps {
           //     withSonarQubeEnv('sonarqube1') {
           //         dir('javaapp-standalone') {
           //             sh "mvn sonar:sonar -Dsonar.projectKey=myapp"
           //         }
          //      }
          //  }
    //    }

        stage('Trivy FS Scan') {
            steps {
                dir('javaapp-standalone') {
                    sh "trivy fs --exit-code 0 --severity HIGH,CRITICAL ."
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('javaapp-standalone') {
                    sh "docker build -t myapp:latest ."
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh "trivy image --scanners vuln --exit-code 0 --severity HIGH,CRITICAL myapp:latest"
            }
        }

        stage('Push to ECR') {
            steps {
                sh """
                    aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 905418283021.dkr.ecr.ap-south-1.amazonaws.com &&
                    docker tag myapp:latest 905418283021.dkr.ecr.ap-south-1.amazonaws.com/javaapp-image:latest &&
                    docker push 905418283021.dkr.ecr.ap-south-1.amazonaws.com/javaapp-image:latest
                """
            }
        }

        stage('Deploy') {
            steps {
                sh """
                    docker stop myapp || true &&
                    docker rm -f myapp || true &&
                    docker pull 905418283021.dkr.ecr.ap-south-1.amazonaws.com/javaapp-image:latest &&
                    docker run -d --name myapp -p 5000:5000 905418283021.dkr.ecr.ap-south-1.amazonaws.com/javaapp-image:latest
                """
                script {
                    def PUBLIC_IP = sh(
                        script: "curl -s http://checkip.amazonaws.com",
                        returnStdout: true
                    ).trim()
                    echo "==================================================="
                    echo " Application deployed successfully! 🎉"
                    echo " Access it here: http://${PUBLIC_IP}:5000"
                    echo "==================================================="
                }
            }
        }
    }
}
